yunionos misc bugfix at 20190410 (#1)
* fix: mptsas not a supported RAID controller

* Add more bnx2x firmware

* add rootfs.201702.11-2.tar, which adds performance testing utilities,
such as lmbench, fio, whetstone, dhrystone

* add rootfs buildroot configuration files and how to

* update: package pxelinux binaries into rpm

diff --git a/bin/mosbundle b/bin/mosbundle
--- a/bin/mosbundle
+++ b/bin/mosbundle
@@ -294,6 +294,10 @@ cp -rf $initramfs_d/* $baremetal_root_fs ||
 echo "wrote ${baremetal_prepare_out}"
 fi
 
+if [ "$src_type_in" == "pxe" ]; then
+	cp -rf ${topdir}/pxelinux/* ${out_d} || fail "failed to copy pxelinux boot files"
+fi
+
 cp "${kernel_d}/${vmlinuz}" "${out_kernel}" ||
 	fail "failed to copy kernel to ${out_kernel}"
 
